---
template_type: surface
template_id: task-surface
template_version: 1
ff_target: machine-dense
ff_band: "15-25"
---
# STELA TASK DASHBOARD
Status: ACTIVE
Owner: Integrator
Last Updated: 2026-02-14

## 1. Session State
Pointer: Session context output (generated by ops/bin/open)
Context Manifest: ops/lib/manifests/CONTEXT.md (checked by tools/lint/context.sh)

Session State contract:
- Session State is pointer-first. Do not write inline branch or hash state here.
- OPEN (and OPEN-PORCELAIN when dirty) is the session state snapshot.
- RESULTS is the audit record for the DP.
- TASK is the stable routing surface.

## 2. Logic Pointers
Primary Constraint: PoT.md (Policy of Truth).
Surface Contract Spec: docs/ops/specs/surfaces/task.md.

### 2.1 Governance Pointers
Jurisdiction: PoT.md Section 3.
Git Authority: PoT.md Section 4.1.
Behavioral Standard: PoT.md Section 4.2.
Staffing Protocol: PoT.md Section 4.1.

### 2.2 Enforcement and Gates
Style: tools/lint/style.sh
Context: tools/lint/context.sh
Truth: tools/lint/truth.sh
DP lint: tools/lint/dp.sh (enforces DP transaction rules in Section 3; does not enforce TASK container schema)
TASK lint: tools/lint/task.sh (sole TASK surface/container schema enforcer)
Repo verify: tools/verify.sh
llms parity: tools/lint/llms.sh

## 3. Current Dispatch Packet (DP)

Section-by-section authoring protocol:
- Generate DP structure from `ops/src/surfaces/dp.md.tpl` using `ops/bin/draft`.
- Do not hand-edit DP structural boilerplate in `TASK.md` after generation.
- Manual edits are limited to slot content only (objective, scope, safety, plan body, receipt body).
- Freeze each completed subsection in order (3.1 -> 3.2 -> 3.3 -> 3.4.x).
- Do not revise earlier sections to justify later work. If scope changes, end the thread and draft a new DP.

Freeze Rule:
- If a completed DP subsection changes later, append an AMENDMENT block in RESULTS; otherwise DP is FAIL.

AMENDMENT: minimum fields
- Reopened section:
- Reason:
- Impact:
- Allowlist change (none or exact paths):

Input discipline (hard rule):
- Worker receives only the DP text. Worker does not require OPEN or DUMP attachments.
- DP writer must not attach or cite disposable artifacts (rough notes, chat logs, scratch drafts, throwaway excerpts).
- DP writer must not include pasted bundles (OPEN, DUMP payloads, manifests) inside the DP body.
- Canon pointers only. Evidence belongs in storage artifacts and RESULTS.

### DP-XXXX: (Template)

## 3.1 Freshness Gate (Must Pass Before Work)
Base Branch: main
Required Work Branch: work/dp-ops-XXXX-YYYY-MM-DD
Base HEAD: 0000000 (Must match session context output)

Required local re-check (worker runs; paste outputs in RESULTS):
- git rev-parse --abbrev-ref HEAD
- git rev-parse --short HEAD
- git status --porcelain

Preconditions:
- No commits on main.
- Working tree must be clean before execution begins.
- If Base HEAD changes, regenerate session artifacts from canonical tools before proceeding.

STOP conditions:
- STOP if any mismatch (branch, Base HEAD, missing work branch).
- STOP if working tree is dirty before execution begins.
- STOP if told to create or switch branches.

## 3.1.1 DP Preflight Gate (Run Before Any Edits)
Purpose:
- Catch malformed DP or TASK schema before work begins.

Worker runs (paste outcome in RESULTS):
- bash tools/lint/dp.sh --test
- bash tools/lint/dp.sh TASK.md
- bash tools/lint/task.sh

STOP if any preflight check fails.

## 3.2 Required Context Load (Read Before Doing Anything)

### 3.2.1 Canon load order (always)
Worker must confirm loaded before edits begin:
1. PoT.md
2. SoP.md
3. PoW.md
4. TASK.md
5. docs/MAP.md
6. docs/MANUAL.md
7. ops/lib/manifests/CONTEXT.md

Notes:
- Worker does not read OPEN. OPEN is for Integrator state refresh and for receipts.
- Disposable artifacts must not be referenced or included.
- Worker input is the DP text only.
- DP writer must not attach or cite disposable artifacts.
- DP writer must not embed pasted bundles.

### 3.2.2 DP-scoped load order (per DP)
- tools/lint/dp.sh
- tools/lint/task.sh
- ops/bin/prune
- docs/ops/specs/surfaces/task.md
- docs/ops/specs/binaries/prune.md
- docs/ops/specs/binaries/open.md (pointer reference only; OPEN behavior is not modified in this DP)

## 3.3 Scope and Safety
Objective: Populate during execution; do not pre-fill in TASK.md.
In scope: Populate during execution; do not pre-fill in TASK.md.
Out of scope: Populate during execution; do not pre-fill in TASK.md.
Safety and invariants: Populate during execution; do not pre-fill in TASK.md.

Target Files allowlist (hard gate):
- storage/dp/active/allowlist.txt

## 3.4 Execution Plan (A–E)

### 3.4.1 State
Populate during execution; do not pre-fill in TASK.md.

### 3.4.2 Request
Populate during execution; do not pre-fill in TASK.md.

### 3.4.3 Changelog
Populate during execution; do not pre-fill in TASK.md.

### 3.4.4 Patch / Diff
Populate during execution; do not pre-fill in TASK.md.

### 3.4.5 Receipt (Proofs to collect) - MUST RUN
- ./ops/bin/open --out=auto --dp="DP-OPS-XXXX"
- ./ops/bin/dump --scope=core --format=chatgpt --out=auto --bundle
- Zero-byte check: test -s <dump_payload_path>
- bash tools/lint/context.sh
- bash tools/lint/style.sh
- bash tools/lint/truth.sh
- bash tools/lint/dp.sh --test
- bash tools/lint/dp.sh TASK.md
- bash tools/lint/task.sh
- bash tools/lint/llms.sh
- ./tools/verify.sh
- ./ops/bin/prune --dry-run
- ./ops/bin/prune --target=pow --dry-run
- bash tools/lint/dp.sh storage/handoff/DP-OPS-XXXX-RESULTS.md
- git diff --name-only
- git diff --stat
- Verify Section 3.5 Closing Block is populated in RESULTS.
- Required pasted outputs: receipts, verification outcomes, and diff output.
- Mandatory Closing Block required in RESULTS.

## 3.5 Closeout (Mandatory Routing)
- Execute docs/MANUAL.md Closeout Cycle in order (Verify, Harvest, Refresh, Log, Prune).
- Update SoP.md and PoW.md with DP entries, including objective summary and verification commands run.
- Protocol order for closeout: Verify -> Generate Results -> COMMIT (Operator Only) -> Prune.
- Run prune hygiene: ./ops/bin/prune --scrub.
- Ensure the next session begins with refreshed session artifacts and matching receipts.

### 3.5.1 Mandatory Closing Block
- Commit Message
- Create Pull Request (Title)
- Create Pull Request (Description)
- Confirm Merge (Commit Message)
- Confirm Merge (Extended Description)
- Confirm Merge (Add a Comment)
