---
template_type: stance
template_id: audit
template_version: 1
ff_target: operator-technical
ff_band: "25-40"
---
Rules:
{{@include:ops/src/shared/stances.json#stance_shared_rules}}
* Generate audit intake with `./ops/bin/bundle --profile=audit --out=auto`.
* Use native profile-prefixed filenames from bundle output (`AUDIT-*` for audit profile); do not relabel artifacts.
* Refresh state using attached bundle artifacts (OPEN and dump pointers come from the bundle).
* Require attached bundle manifest `resolved_profile=audit`; if not, **STOP** and request a correct audit bundle.
* If user text is empty and required attachments are present, proceed and emit only the final audit block.
* `--profile=addenda` is addenda mode and is never valid for audit verdict workflows.
* If interpretation conflicts with receipt command outputs, treat command outputs and lint results as authoritative and mark the interpretation as non-blocking.
* For allowlist interpretation, `tools/lint/integrity.sh` plus certify changed-file subset check are authoritative; raw `comm` output is informational.
* Logic: `PoT.md`. Structure: `TASK.md` + `ops/src/surfaces/dp.md.tpl`.

Steps:
0. **PRECONDITIONS**: If bundle artifact, bundle manifest, or `storage/handoff/RESULTS.md` is missing: **STOP**.
1. **PoT Compliance**: Identify canon drift, ambiguity glossing, invented paths, or disposable-artifact dependence.
2. **DP Integrity**:
   * Confirm DP structure matches `ops/src/surfaces/dp.md.tpl` using TASK evidence from dump payload.
   * Confirm Section 3.2 includes the Contractor brief include and no disposable artifact citations.
   * Verify lint proofs: `bash tools/lint/task.sh` and `bash tools/lint/dp.sh TASK.md`.
3. **RECEIPTS**: Confirm the RESULTS receipt at `storage/handoff/RESULTS.md` was generated by `ops/bin/certify` (tool-generated artifact - manually authored receipts are a hard FAIL).
   * Confirm Section 3.4.5 uses template-injected mandatory receipt stubs and limits scope-specific commands to the `RECEIPT_EXTRA` slot.
   * Verify `tools/lint/results.sh` passes against the receipt: template structure matches `ops/src/surfaces/results.md.tpl`, recorded git hash equals HEAD at closeout, and the Contractor Execution Narrative includes required subheadings and Decision Leaf lines.
   * Verify `ops/bin/certify` maintained strict closing sidecar validation as a hard gate.
   * Verify `tools/lint/integrity.sh` passed (its output must appear in the receipt's Scope Verification section).
   * Reject "trust me" receipts, missing outputs, or receipts with unresolved slot tokens.
4. **ALLOWLIST**: Verify `storage/dp/active/allowlist.txt` exists and contains all changed files.
5. **DRIFT**: No out-of-scope edits. Default dump scope is `--scope=core`, which structurally excludes `opt/_factory/`. Any session using `--scope=platform` or `--scope=factory` must carry explicit authorization.
6. **GENERATED OUTPUTS**: Require tool-based regeneration proofs (no manual edits to manifests, llms bundles, dumps, or RESULTS receipts).

Output only: Complete audit report.
{{@include:ops/src/shared/stances.json#single_fence_contract_rules}}
First line must be ```markdown.
First non-empty line inside the fenced block must start with `**AUDIT -`.
Last line must be ``` .
Do not render markdown outside the fence; emit all report characters literally inside the fenced block.
Do not emit citation tokens (`[cite_start]`, `[cite:`, `[/cite]`, `:contentReference[`, or `oaicite`).
